// components/ExportReport.jsx
import { motion } from "framer-motion";
import { FiDownload, FiFileText } from "react-icons/fi";
import { useState } from "react";

const ExportReport = ({ analysisData, fileName = "resume-analysis" }) => {
  const [isExporting, setIsExporting] = useState(false);

  const exportToPDF = async () => {
    setIsExporting(true);
    try {
      // Create HTML content for PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <title>Resume Analysis Report</title>
          <style>
            body {
              font-family: 'Arial', sans-serif;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px;
              color: #333;
            }
            .header {
              text-align: center;
              margin-bottom: 40px;
              border-bottom: 3px solid #3b82f6;
              padding-bottom: 20px;
            }
            .header h1 {
              color: #3b82f6;
              margin: 0;
              font-size: 32px;
            }
            .header p {
              color: #666;
              margin: 10px 0 0;
            }
            .score-section {
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              color: white;
              padding: 30px;
              border-radius: 12px;
              margin: 30px 0;
              text-align: center;
            }
            .score-section h2 {
              margin: 0;
              font-size: 48px;
            }
            .section {
              margin: 30px 0;
            }
            .section h3 {
              color: #3b82f6;
              border-bottom: 2px solid #e5e7eb;
              padding-bottom: 10px;
              margin-bottom: 15px;
            }
            .section ul {
              list-style-type: none;
              padding: 0;
            }
            .section li {
              padding: 10px;
              margin: 8px 0;
              background: #f9fafb;
              border-left: 4px solid #3b82f6;
              border-radius: 4px;
            }
            .footer {
              margin-top: 50px;
              text-align: center;
              color: #999;
              border-top: 1px solid #e5e7eb;
              padding-top: 20px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>📄 Resume Analysis Report</h1>
            <p>Generated by Resumate AI</p>
            <p>${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </div>
          
          ${analysisData?.score ? `
          <div class="score-section">
            <h2>${analysisData.score}%</h2>
            <p>Overall Resume Score</p>
          </div>
          ` : ''}
          
          ${analysisData?.strengths?.length ? `
          <div class="section">
            <h3>✅ Strengths</h3>
            <ul>
              ${analysisData.strengths.map(item => `<li>${item}</li>`).join('')}
            </ul>
          </div>
          ` : ''}
          
          ${analysisData?.weaknesses?.length ? `
          <div class="section">
            <h3>⚠️ Areas for Improvement</h3>
            <ul>
              ${analysisData.weaknesses.map(item => `<li>${item}</li>`).join('')}
            </ul>
          </div>
          ` : ''}
          
          ${analysisData?.suggestions?.length ? `
          <div class="section">
            <h3>💡 Suggestions</h3>
            <ul>
              ${analysisData.suggestions.map(item => `<li>${item}</li>`).join('')}
            </ul>
          </div>
          ` : ''}
          
          ${analysisData?.keywords?.length ? `
          <div class="section">
            <h3>🔑 Key Keywords Detected</h3>
            <ul>
              ${analysisData.keywords.map(item => `<li>${item}</li>`).join('')}
            </ul>
          </div>
          ` : ''}
          
          <div class="footer">
            <p><strong>Resumate AI</strong> - Empowering Your Career Journey</p>
            <p>This report was automatically generated. For best results, implement the suggestions and re-analyze your resume.</p>
          </div>
        </body>
        </html>
      `;

      // Create a Blob and download
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${fileName}-${Date.now()}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      // Note: For actual PDF generation, you would need a library like jsPDF or html2pdf
      // This exports as HTML which can be printed/saved as PDF by the user
    } catch (error) {
      console.error("Export failed:", error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <motion.button
      onClick={exportToPDF}
      disabled={isExporting || !analysisData}
      whileHover={{ scale: 1.05 }}
      whileTap={{ scale: 0.95 }}
      className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition ${
        isExporting || !analysisData
          ? "bg-gray-300 dark:bg-gray-700 text-gray-500 cursor-not-allowed"
          : "bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-md hover:shadow-lg"
      }`}
    >
      {isExporting ? (
        <>
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
          >
            <FiFileText className="w-5 h-5" />
          </motion.div>
          <span>Exporting...</span>
        </>
      ) : (
        <>
          <FiDownload className="w-5 h-5" />
          <span>Export Report</span>
        </>
      )}
    </motion.button>
  );
};

export default ExportReport;
